### ISSUE TITLE
[BUG] The time with one-digit minutes is displayed as a one-digit .

### ISSUE THREAD

**Issue by gitpower2017** [arvage/nighttime#1]
Hello,

The time 20:00 is displayed as 20:0.
Or sunrise: "7:8"

`sNight : msg : Object
object
payload: false
topic: "isNight"
nauticalDawn: "6:0"
dawn: "6:37"
sunrise: "7:8"
sunriseEnd: "7:12"
goldenHourEnd: "7:49"
goldenHour: "19:20"
sunsetStart: "19:57"
sunset: "20:0"
dusk: "20:31"
nauticalDusk: "21:9"
night: "21:48"
_msgid: "78a3b0a0.91468"
`

**Comment by mrdvt92** [comment]
In the nighttime.js

Lines like this

`var nauticalDawnStr = times.nauticalDawn.getHours() + ':' + times.nauticalDawn.getMinutes();`

need to use a formatter like `sprintf("%02d:%02d", hour, min)`.

**Comment by mrdvt92** [comment]
This should do it.

```
- var nauticalDawnStr = times.nauticalDawn.getHours() + ':' + times.nauticalDawn.getMinutes();
+ var nauticalDawnStr = times.nauticalDawn.format("HH:MM");
```

**Comment by arvage** [comment]
made a slight change and now it is returning 2 digits for both hours and minutes.
